version: '3.9'
services:
  broker:
    container_name: mosquitto_broker
    image: eclipse-mosquitto:latest
    volumes:
     - mosquitto_data:/mosquitto
    networks:
     - example_experiment_network
  orquestrator:
    container_name: orquestrator
    image: mqttdb/orquestrator:1
    ports:
      - 8000:8000
    networks:
     - example_experiment_network
    environment:
      - tolerance=5
      - broker=mosquitto_broker
    depends_on:
      - broker
  workers:
    container_name: worker
    image: mqttdb/worker:1
    networks:
     - example_experiment_network
    environment:
      - broker=mosquitto_broker
      - login_t=30
      - timeout=5
      - tool=source/tools/mqttloader/bin/mqttloader
    depends_on:
      - orquestrator
networks:
  example_experiment_network:
    driver: bridge
volumes:
  mosquitto_data:
