version: '3.9'
services:
  broker:
    container_name: mosquitto_broker
    image: eclipse-mosquitto:latest
    volumes:
     - ./mosquitto.confg:/mosquitto/config/mosquitto.conf
     - mosquitto_data:/mosquitto
    networks:
     - example_experiment_network
  target:
    container_name: test_broker
    image: eclipse-mosquitto:latest
    volumes:
     - ./mosquitto.confg:/mosquitto/config/mosquitto.conf
    networks:
     - example_experiment_network
  orquestrator:
    build:
      context: ./
      dockerfile: ./images/orquestrator/Dockerfile
    ports:
      - 8000:8000
    networks:
     - example_experiment_network
    environment:
      - TOLERANCE=10
      - BROKER=tcp://mosquitto_broker:1883
    depends_on:
      - broker
  web:
    build:
      context: ./
      dockerfile: ./images/web/Dockerfile
    ports:
      - 3001:3000
    networks:
     - example_experiment_network
    depends_on:
      - orquestrator
  workers:
    build:
      context: ./
      dockerfile: ./images/worker/Dockerfile
    networks:
     - example_experiment_network
    environment:
      - BROKER=tcp://mosquitto_broker:1883
      - LTIMEOUT=30
      - LTHRESHOUT=3
    depends_on:
      - orquestrator
  workers-2:
    build:
      context: ./
      dockerfile: ./images/worker/Dockerfile
    networks:
     - example_experiment_network
    environment:
      - BROKER=tcp://mosquitto_broker:1883
      - LTIMEOUT=30
      - LTHRESHOUT=3
    depends_on:
      - workers
  workers-3:
    build:
      context: ./
      dockerfile: ./images/worker/Dockerfile
    networks:
     - example_experiment_network
    environment:
      - BROKER=tcp://mosquitto_broker:1883
      - LTIMEOUT=30
      - LTHRESHOUT=3
    depends_on:
      - workers-2
networks:
  example_experiment_network:
    driver: bridge
volumes:
  mosquitto_data:
